### ISSUE TITLE
Dashboard tab

### ISSUE THREAD

**Issue by nassimerrahoui** [jhipster/jhipster-control-center#112]
Currently, there is a dashboard tab which is not use for the moment. I open this ticket to allow us to put some ideas here of how we can use this tab or if we can remove it. Please, feel free to participate with any idea that pops into your mind :+1: 

![jhcc](https://user-images.githubusercontent.com/23552990/97870156-db40b580-1d12-11eb-8721-104853dde158.png)

**Comment by nassimerrahoui** [comment]
Closing this issue because of #134

**Comment by pascalgrimaud** [comment]
Thanks @nassimerrahoui, forgot to add `fix https://github.com/jhipster/jhipster-control-center/issues/112` in my PR. It's done now
