### ISSUE TITLE
Add UI for more actuator endpoints

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/jhipster-control-center#117]
We want as many actuator endpoints as possible to be available in the JHipster Control Center UI.

1. The available actuator endpoints for the current application can be retrieved by querying: `/management/`, you will retrieve something like that:
```
{
  "_links" : {
    "self" : {
      "href" : "http://localhost:7419/management",
      "templated" : false
    },
[...]
    "health" : {
      "href" : "http://localhost:7419/management/health",
      "templated" : false
    },
    "loggers" : {
      "href" : "http://localhost:7419/management/loggers",
      "templated" : false
    },
    "threaddump" : {
      "href" : "http://localhost:7419/management/threaddump",
      "templated" : false
    },
  }
}
```
2. Only present the UI element if the endpoint is present in above response
3. Implement UI for those endpoints (see the [actuator endpoint list](https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-endpoints) and [actuator endpoint docs](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/actuator-api/html/#overview), some of them might have to be enabled on `management.endpoints.web.exposure.include`):
- [x] `/management/caches` (can be a `cache` button + popup window available from the instance view). More than just viewing the caches, you can also do some actions on them such as evict them
- [x] `/management/liquibase` (can be a `db migrations` button + popup window available from the instance view)
- [ ] `/management/threaddump` (can be a button on the health page to download the file)
- [ ] `/management/startup` + `/management/mappings` + `/management/scheduledtasks` (can be a `spring` button + a popup window available from the instance view)

4. If you find the new management endpoint useful, please submit a PR to generator-jhipster to enable it by default for new jhipster apps

**Comment by nassimerrahoui** [comment]
The actuator endpoint _startup_ was introduce in Spring Boot 2.4 and it must be used with BufferingApplicationStartup.class in each application that we want to get startup events. We have to wait the upgrade to Spring Boot 2.4

generator-jhipster#13237

**Comment by nassimerrahoui** [comment]
The actuator endpoint _threaddump_ is already use in metrics page but we cannot download this dump
