### ISSUE TITLE
Instances page: consistency

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-control-center#13]
We need consistency:
- url: http://localhost:1337/applications/jhi-applications
- navbar menu: Applications > Services
- title of page: Applications Instances

I'd suggest to change:
- url: http://localhost:1337/applications/instances
-navbar menu: Applications > Instances
- title of page: Applications Instances

What do you think ?

**Comment by nassimerrahoui** [comment]
> We need consistency:
> 
> * url: http://localhost:1337/applications/jhi-applications
> * navbar menu: Applications > Services
> * title of page: Applications Instances
> 
> I'd suggest to change:
> 
> * url: http://localhost:1337/applications/instances
>   -navbar menu: Applications > Instances
> * title of page: Applications Instances
> 
> What do you think ?

Yes, this page is a list of applications instances, I will change it
