### ISSUE TITLE
Improve instance view for static profile

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/jhipster-control-center#136]
The instance view (in static mode) could be improved to show more information about currently running instances. As this is the static mode, instance info cannot be retrieved from a discovery server as they have to be fetched directly from the instances management endpoints.

![Screenshot-20201220181939-1277x493](https://user-images.githubusercontent.com/513471/102719724-ee720980-42ef-11eb-8380-715e7a8b2d13.png)

- [ ] In the instance column, display the instances IP address.
- [ ] In the profile column, display the instances profiles from their /info endpoint (if available)
- [ ] In the git column, which should probably be called "version" instead, display the instance's version
- [ ] It would also be nice to display the UP/DOWN status of the app from the /health endpoint.

**Comment by pascalgrimaud** [comment]
Closed by https://github.com/jhipster/jhipster-control-center/pull/169

**Comment by matteo-png** [comment]
https://opencollective.com/generator-jhipster/expenses/43291

**Comment by pascalgrimaud** [comment]
@matteo-png : bounty approved, thanks for your work
