### ISSUE TITLE
[Reactive] Broken Swagger with Microservices

### ISSUE THREAD

**Issue by nassimerrahoui** [jhipster/jhipster-control-center#150]
Related to jhipster/generator-jhipster#13444 which is fixed for Spring MVC but not for Spring WebFlux.

In OpenAPI 3.0, servers array specify one or more base URLs for API. Servers replaces the host, basePath and schemes keywords used in OpenAPI 2.0. _(see : https://swagger.io/docs/specification/api-host-and-base-path/)_

Suggested ideas but not sure if it works :

- We can use a custom implementation of WebFluxSwaggerTransformationFilter _(see springfox/springfox#3483)_
- We can use a custom GatewayFilter from Spring Cloud Gateway to modify servers

**Comment by pascalgrimaud** [comment]
@nassimerrahoui : I confirm the issue
