### ISSUE TITLE
Swagger UI broken for Microservices when compression is true

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-control-center#163]
Similar to https://github.com/jhipster/generator-jhipster/issues/14198

But before calling Microservices, there is call to https://github.com/jhipster/jhipster-control-center/blob/main/src/main/java/tech/jhipster/controlcenter/config/apidoc/SwaggerConfiguration.java#L68 
Maybe it's the reason

**Comment by nassimerrahoui** [comment]
@pascalgrimaud I can't reproduce the behavior, how did you test it ? I tested with prod + static and prod + consul profiles with jwt authentication

**Comment by pascalgrimaud** [comment]
Use these following steps to reproduce:

Create projects:
- in a new folder: `jhipster jdl https://raw.githubusercontent.com/pascalgrimaud/microservices-demo/main/microservices-demo.jdl`

Gateway:
- `cd gateway/`
- `npm run docker:others:up`
- `npm run docker:db:up`
- build: `./mvnw clean verify -Pprod -DskipTests`
- start with prod profile: `java -jar target/*.jar --spring.profiles.active=prod,api-docs`

Store:
- `cd store/`
- `npm run docker:db:up`
- build: `./mvnw clean verify -Pprod -DskipTests`
- start with prod profile: `java -jar target/*.jar --spring.profiles.active=prod,api-docs`

Invoice:
- `cd invoice/`
- `npm run docker:db:up`
- build: `./mvnw clean verify -Pprod -DskipTests`
- start with dev profile: `java -jar target/*.jar --spring.profiles.active=dev,api-docs`

JHCC:
- go in this project
- build Docker image `docker build -t jhipster/jhipster-control-center:local .`
- go back into gateway
- edit `src/main/docker/jhipster-control-center.yml` and use `jhipster/jhipster-control-center:local` image instead
- maybe change to `consul:8500`
- start it: `docker-compose -f src/main/docker/jhipster-control-center.yml up`
- go into swagger and try API
- only `invoice` works

**Comment by pascalgrimaud** [comment]
I can't reproduce any more. It seems to be fixed.
So let's close this
