### ISSUE TITLE
CI: e2e tests

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-control-center#26]
We should add protractor tests, and check the new pages too

**Comment by sendilkumarn** [comment]
Can we use Cypress tests here, instead of Protractor?

**Comment by pascalgrimaud** [comment]
I'd like too. There is already an PR to use Cypress with Vue.js :
https://github.com/jhipster/jhipster-vuejs/pull/399

It was in "hold on" state, as it was said that we should be consistent between our front: Angular and React
