### ISSUE TITLE
CSS: dashboard

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-control-center#36]
Suggestions from @PierreBesson :
- https://github.com/tabler/tabler
- https://startbootstrap.com/themes/sb-admin-2/
- https://coreui.io/
- https://github.com/ColorlibHQ/AdminLTE

Before starting this, we need to check if the template is "free" and "open source".

As I'm not a front guy, I don't know if it's easy to integrate it to this application.
Another important part is to keep in mind: if possible, use the side-by-side approch in front too: so it will be easier to upgrade the project

@sendilkumarn : as you tell me you want to take part to this project too, is it something you already did ? Is it easy to replace and use another bootstrap template ?

**Comment by myc31** [comment]
Some more free & open source templates suggestions:

- [vue-element-admin](https://github.com/PanJiaChen/vue-element-admin) :  [Live Demo](https://panjiachen.github.io/vue-element-admin/#/dashboard)
- [vuestic-admin](https://github.com/epicmaxco/vuestic-admin) : [Live Demo](https://vuestic.epicmax.co/admin/dashboard)
- [shard-dashboard-vue](https://github.com/DesignRevision/shards-dashboard-vue) : [Live Demo](https://designrevision.com/demo/shards-dashboard-lite-vue)

**Comment by sendilkumarn** [comment]
The difficulty level depends on the library. But in general, it is a lot of work. To minimise the amount of work, we should look for some bootstrap + vue supported template, looks like shard-dashboard-vue supports both. 

But the other part of the story, what is the idea that you have in mind for the dashboards? 

> Do you want it completely configurable by the end user?
     If not, then we can use some charting library like e-charts / D3 to solve that. 

Also, do we have a general idea of what we are gonna show in the dashboards here?

**Comment by pascalgrimaud** [comment]
That's one of the reason why I suggested to use first bootswatch. It's easy and don't consume time.
So this ticket can be done later, no need to focus time on this as we don't know exactly which dashboards we'll have

**Comment by deepu105** [comment]
Also keep in mind that if you switch to a admin framework/theme, upgrading
yo different Jhipster versions will be lot of work as well

**Comment by pascalgrimaud** [comment]
Closing this as we'll keep bootswatch and improve it
