### ISSUE TITLE
Change default port: 1337 -> 7419

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-control-center#51]
Look at https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers
1337 can already be used.

For JHipster Control Center, I suggest: 7419 -> JHIP
And 7419 is not used in the [list](https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers)

What do you think @PierreBesson ?

**Comment by PierreBesson** [comment]
Yes it looks OK but not too easy to remember.

**Comment by jdubois** [comment]
I would keep 1337 for the apps that we generate. I see in the list that it's being used by sails.js, which is a kind of competitor, so that's cool (it would be weird that people use both in parallel).

**Comment by pascalgrimaud** [comment]
I suggested to change and go away from 1337, as it's related to some 'hack' and try to have our own default port, instead of using a common one
Of course, it can be discussed as it will only be the default port. 
About me, I already use this application for my customer and override the 1337 by 7419

**Comment by pascalgrimaud** [comment]
If someone else prefers to keep 1337, this PR can be reverted
What do you think @PierreBesson @nassimerrahoui @adilabed ?

**Comment by jdubois** [comment]
@pascalgrimaud I totally agree for the control center -> it should not have the same port as default apps, and I would keep 1337 for default apps, maybe, in the future

**Comment by nassimerrahoui** [comment]
I think we can keep 7419 for control center and maybe make 1337 as default port for generated apps as you said

**Comment by adilabed** [comment]
I also think JHCC should have its own default port (7419)

**Comment by PierreBesson** [comment]
+1 for 7419 for control center, 1337 for apps in Dev, 8080 for apps is prod.
