### ISSUE TITLE
SonarCloud analysis

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-control-center#9]
The analysis should be there https://sonarcloud.io/organizations/jhipster/projects

**Comment by pascalgrimaud** [comment]
before doing this, we need to fix the current Sonar Analyze, as it's pretty bad

**Comment by SudharakaP** [comment]
@pascalgrimaud : If you want to use CodeQL instead or in addition to this let me know. I can add this similar to the one [I added at jhipster-online](https://github.com/jhipster/jhipster-online/issues/192). :smile:

**Comment by pascalgrimaud** [comment]
@SudharakaP I don't use CodeQL. Cna you tell me the difference with SonarCloud ?

**Comment by SudharakaP** [comment]
@pascalgrimaud : [CodeQL Analysis](https://github.com/github/codeql-action) only detect vulnerabilities at the moment. I think SonarCloud is more comprehensive; for example it detects test coverage, duplicate or overly complex logic in code etc in addition to vulnerabilities. I haven't done a comprehensive comparison of the two, but from what I observe that seems to be the case.

**Comment by pascalgrimaud** [comment]
So I think we should be consistent. We already use SonarCloud for analyzing our default sample from generator-jhipster
Then, I just need to find time to configure it, for this project. But before doing this, I know there are a lot of fix to do :-D

**Comment by SudharakaP** [comment]
@pascalgrimaud : Yes, since SonarCloud is comprehensive I think it takes some effort to maintain it which is why I integrated CloudQL instead in jhipster-online. I would suggest adding SonarCloud analysis to PRs like we do in [jhipster-dotnetcore](https://github.com/jhipster/jhipster-dotnetcore); I think that might be a good way that code quality is maintained without trying to do it after commits are made.

**Comment by pascalgrimaud** [comment]
The Sonar Analyze is here: https://sonarcloud.io/dashboard?id=jhipster_jhipster-control-center

But I'm reopening this because:
- need to add badge in README
- need to exclude master branch / fork - maybe something similar to https://github.com/jhipster/generator-jhipster/blob/master/test-integration/scripts/25-sonar-analyze.sh#L10
- about the low coverage, 57.9%, I'm not sure we can do something, as it's related to https://github.com/jhipster/jhipster-vuejs/issues/431 which is not done yet. Maybe we can ignore the TS part until it is fixed on SonarCloud side ?

**Comment by avdev4j** [comment]
I think we should open an issue to improve the readme as it needs more than a badge (imho). 
I've juste exclude the branch/fork other than master.
@nassimerrahoui is working on the code coverage and a PR is in progress but if there is a know bug I suggest to follow your advice @pascalgrimaud .
