### ISSUE TITLE
Unique management port of monitored apps is a constraint

### ISSUE THREAD

**Issue by gmarziou** [jhipster/jhipster-control-center#98]
Hi,

From the slides in the meetup, it seems that the JHCC connects to management port of apps using 9999 for all of them.

This prevents from running several apps on same computer, either in deployment or development.

Why not using a different port per app?

This port could be published by the app in the service registry or when there's no registry it could be an offset from API port.

For a similar requirement, hazelcast-eureka uses Eureka client registration metadata so that apps can publish their hazelcast port: https://github.com/hazelcast/hazelcast-eureka#reusing-existing-eurekaclient-instance

**Comment by nassimerrahoui** [comment]
Hello @gmarziou

Thank you for your ticket.

JHCC doesn't use 9999 port for all of them. Each app publish its port in the service registry.

In the meetup slides, it was an example to get a dedicated management port in the future of JHCC (cf. [https://github.com/jhipster/generator-jhipster/blob/master/rfcs/2-jhipster-rfc-jhipster-control-center.md#guide-level-explanation](https://github.com/jhipster/generator-jhipster/blob/master/rfcs/2-jhipster-rfc-jhipster-control-center.md#guide-level-explanation)).

**Comment by PierreBesson** [comment]
@gmarziou Right now this is not implemented but My idea was that if you set `management.port=9999` on your app then the actuator endpoints would be exposed on a different port. Ultimately the point was just that this port should be different that the "main server" port for increased security. I guess if you are running apps on the same machine you could have different management ports for different apps.
To get this port dynamically on the JHCC, I guess it could be set as instance metadata (like the spring profile is set today). I will open a separate issue on generator-jhipster about the management.port property.

**Comment by PierreBesson** [comment]
Let's continue the discussion on the generator-jhipster issue : https://github.com/jhipster/generator-jhipster/issues/12184
